"""initial migration

Revision ID: 0ca408e8ad57
Revises: 
Create Date: 2026-02-10 19:03:06.917567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ca408e8ad57'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Roles',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=True),
    sa.Column('ModifiedAt', sa.DateTime(), nullable=True),
    sa.Column('CreatedBy', sa.String(length=100), nullable=True),
    sa.Column('ModifiedBy', sa.String(length=100), nullable=True),
    sa.Column('IsDeleted', sa.Boolean(), nullable=True),
    sa.Column('IsActive', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Users',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('FirstName', sa.String(length=100), nullable=False),
    sa.Column('MiddleName', sa.String(length=100), nullable=True),
    sa.Column('LastName', sa.String(length=100), nullable=True),
    sa.Column('Age', sa.Integer(), nullable=True),
    sa.Column('Gender', sa.String(length=10), nullable=True),
    sa.Column('Dob', sa.Date(), nullable=True),
    sa.Column('Address', sa.String(length=255), nullable=True),
    sa.Column('Country', sa.String(length=100), nullable=True),
    sa.Column('PhoneNumber', sa.String(length=20), nullable=True),
    sa.Column('Email', sa.String(length=100), nullable=False),
    sa.Column('Password', sa.String(length=255), nullable=False),
    sa.Column('Image', sa.String(length=255), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=True),
    sa.Column('ModifiedAt', sa.DateTime(), nullable=True),
    sa.Column('CreatedBy', sa.String(length=100), nullable=True),
    sa.Column('ModifiedBy', sa.String(length=100), nullable=True),
    sa.Column('IsDeleted', sa.Boolean(), nullable=True),
    sa.Column('IsActive', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Email')
    )
    op.create_table('EmailSettings',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('SmtpServer', sa.String(length=255), nullable=False),
    sa.Column('SmtpPort', sa.Integer(), nullable=False),
    sa.Column('EmailAddress', sa.String(length=100), nullable=False),
    sa.Column('Password', sa.String(length=1000), nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=True),
    sa.Column('ModifiedAt', sa.DateTime(), nullable=True),
    sa.Column('CreatedBy', sa.String(length=100), nullable=True),
    sa.Column('ModifiedBy', sa.String(length=100), nullable=True),
    sa.Column('IsDeleted', sa.Boolean(), nullable=True),
    sa.Column('IsActive', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['UserId'], ['Users.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Resumes',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.Column('FullName', sa.String(length=100), nullable=False),
    sa.Column('Email', sa.String(length=150), nullable=False),
    sa.Column('PhoneNumber', sa.String(length=20), nullable=True),
    sa.Column('Address', sa.String(length=255), nullable=False),
    sa.Column('DateOfBirth', sa.String(length=20), nullable=True),
    sa.Column('Gender', sa.String(length=10), nullable=True),
    sa.Column('Country', sa.String(length=100), nullable=True),
    sa.Column('Nationality', sa.String(length=100), nullable=True),
    sa.Column('ProfileImage', sa.String(length=255), nullable=True),
    sa.Column('ResumeFile', sa.String(length=255), nullable=True),
    sa.Column('Summary', sa.Text(), nullable=True),
    sa.Column('Objective', sa.Text(), nullable=True),
    sa.Column('Education1', sa.String(length=255), nullable=True),
    sa.Column('Education2', sa.String(length=255), nullable=True),
    sa.Column('Education3', sa.String(length=255), nullable=True),
    sa.Column('DeveloperType', sa.String(length=255), nullable=False),
    sa.Column('Skills', sa.Text(), nullable=False),
    sa.Column('ExperienceTitle', sa.String(length=100), nullable=True),
    sa.Column('ExperienceCompany', sa.String(length=100), nullable=True),
    sa.Column('ExperienceDuration', sa.String(length=50), nullable=True),
    sa.Column('TotalExperience', sa.String(length=50), nullable=True),
    sa.Column('ExperienceDescription', sa.Text(), nullable=True),
    sa.Column('Project1', sa.Text(), nullable=True),
    sa.Column('Project2', sa.Text(), nullable=True),
    sa.Column('Languages', sa.String(length=255), nullable=True),
    sa.Column('LinkedIn', sa.String(length=255), nullable=True),
    sa.Column('GitHub', sa.String(length=255), nullable=True),
    sa.Column('Certifications', sa.Text(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=True),
    sa.Column('ModifiedAt', sa.DateTime(), nullable=True),
    sa.Column('CreatedBy', sa.String(length=100), nullable=True),
    sa.Column('ModifiedBy', sa.String(length=100), nullable=True),
    sa.Column('IsDeleted', sa.Boolean(), nullable=True),
    sa.Column('IsActive', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['UserId'], ['Users.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('SentEmail',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('FromEmail', sa.String(length=255), nullable=False),
    sa.Column('ToEmail', sa.Text(), nullable=False),
    sa.Column('Subject', sa.String(length=500), nullable=True),
    sa.Column('Body', sa.Text(), nullable=True),
    sa.Column('MessageId', sa.String(length=255), nullable=True),
    sa.Column('ParentMessageId', sa.String(length=255), nullable=True),
    sa.Column('ThreadId', sa.String(length=255), nullable=True),
    sa.Column('Status', sa.String(length=50), nullable=False),
    sa.Column('ScheduledTime', sa.DateTime(), nullable=True),
    sa.Column('SentAt', sa.DateTime(), nullable=True),
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=True),
    sa.Column('ModifiedAt', sa.DateTime(), nullable=True),
    sa.Column('CreatedBy', sa.String(length=100), nullable=True),
    sa.Column('ModifiedBy', sa.String(length=100), nullable=True),
    sa.Column('IsDeleted', sa.Boolean(), nullable=True),
    sa.Column('IsActive', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['UserId'], ['Users.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('UserRoles',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.Column('RoleId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['RoleId'], ['Roles.Id'], ),
    sa.ForeignKeyConstraint(['UserId'], ['Users.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('EmailReply',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ReplyMessageId', sa.String(length=255), nullable=False),
    sa.Column('InReplyTo', sa.String(length=255), nullable=False),
    sa.Column('FromEmail', sa.String(length=255), nullable=False),
    sa.Column('ToEmail', sa.Text(), nullable=False),
    sa.Column('Subject', sa.String(length=500), nullable=True),
    sa.Column('Html', sa.Text(), nullable=True),
    sa.Column('Text', sa.Text(), nullable=True),
    sa.Column('IsSeen', sa.Boolean(), nullable=False),
    sa.Column('SentEmailId', sa.Integer(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=True),
    sa.Column('ModifiedAt', sa.DateTime(), nullable=True),
    sa.Column('CreatedBy', sa.String(length=100), nullable=True),
    sa.Column('ModifiedBy', sa.String(length=100), nullable=True),
    sa.Column('IsDeleted', sa.Boolean(), nullable=True),
    sa.Column('IsActive', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['SentEmailId'], ['SentEmail.Id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('ReplyMessageId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('EmailReply')
    op.drop_table('UserRoles')
    op.drop_table('SentEmail')
    op.drop_table('Resumes')
    op.drop_table('EmailSettings')
    op.drop_table('Users')
    op.drop_table('Roles')
    # ### end Alembic commands ###
