"""Add created by user id in all tables

Revision ID: 1f31e08055f8
Revises: 0ca408e8ad57
Create Date: 2026-02-10 19:33:31.582646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f31e08055f8'
down_revision: Union[str, Sequence[str], None] = '0ca408e8ad57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EmailReply', sa.Column('CreatedByUserId', sa.Integer(), nullable=True))
    op.add_column('EmailSettings', sa.Column('CreatedByUserId', sa.Integer(), nullable=True))
    op.add_column('Resumes', sa.Column('CreatedByUserId', sa.Integer(), nullable=True))
    op.add_column('Roles', sa.Column('CreatedByUserId', sa.Integer(), nullable=True))
    op.add_column('SentEmail', sa.Column('CreatedByUserId', sa.Integer(), nullable=True))
    op.add_column('Users', sa.Column('CreatedByUserId', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'CreatedByUserId')
    op.drop_column('SentEmail', 'CreatedByUserId')
    op.drop_column('Roles', 'CreatedByUserId')
    op.drop_column('Resumes', 'CreatedByUserId')
    op.drop_column('EmailSettings', 'CreatedByUserId')
    op.drop_column('EmailReply', 'CreatedByUserId')
    # ### end Alembic commands ###
