"""Add UserId to Resume

Revision ID: 227b17cdc561
Revises: 
Create Date: 2025-08-04 15:31:50.066972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '227b17cdc561'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Resumes', sa.Column('UserId', sa.Integer(), nullable=False))
    op.alter_column('Resumes', 'ExperienceDescription',
               existing_type=sa.TEXT(length=2147483647, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_foreign_key(None, 'Resumes', 'Users', ['UserId'], ['Id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Resumes', type_='foreignkey')
    op.alter_column('Resumes', 'ExperienceDescription',
               existing_type=sa.Text(),
               type_=sa.TEXT(length=2147483647, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    op.drop_column('Resumes', 'UserId')
    # ### end Alembic commands ###
