"""Add Country colum to Resume

Revision ID: 278e6b8d69ef
Revises: 590743d1050f
Create Date: 2025-08-08 19:16:27.981854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '278e6b8d69ef'
down_revision: Union[str, Sequence[str], None] = '590743d1050f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Resumes', sa.Column('Country', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Resumes', 'Country')
    # ### end Alembic commands ###
