"""Update Resume by removing extra fields

Revision ID: 590743d1050f
Revises: a1c7bb8526cf
Create Date: 2025-08-08 18:44:41.425889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '590743d1050f'
down_revision: Union[str, Sequence[str], None] = 'a1c7bb8526cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Resumes', 'IsActive',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.drop_column('Resumes', 'UpdatedAt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Resumes', sa.Column('UpdatedAt', sa.DATETIME(), autoincrement=False, nullable=True))
    op.alter_column('Resumes', 'IsActive',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
