"""Add DeveloperType to Resumes

Revision ID: 8d2a44dd1ed1
Revises: 227b17cdc561
Create Date: 2025-08-05 19:46:17.376305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d2a44dd1ed1'
down_revision: Union[str, Sequence[str], None] = '227b17cdc561'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Resumes', sa.Column('DeveloperType', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Resumes', 'DeveloperType')
    # ### end Alembic commands ###
