"""Add audit columns to Resume

Revision ID: a1c7bb8526cf
Revises: 8d2a44dd1ed1
Create Date: 2025-08-08 18:41:26.901156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1c7bb8526cf'
down_revision: Union[str, Sequence[str], None] = '8d2a44dd1ed1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Resumes', sa.Column('ModifiedAt', sa.DateTime(), nullable=True))
    op.add_column('Resumes', sa.Column('CreatedBy', sa.String(length=100), nullable=True))
    op.add_column('Resumes', sa.Column('ModifiedBy', sa.String(length=100), nullable=True))
    op.add_column('Resumes', sa.Column('IsDeleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Resumes', 'IsDeleted')
    op.drop_column('Resumes', 'ModifiedBy')
    op.drop_column('Resumes', 'CreatedBy')
    op.drop_column('Resumes', 'ModifiedAt')
    # ### end Alembic commands ###
